[package]
name = "minimal"
authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wslplugins-rs = { path = "../../crates/wslplugins-rs", features = [
  "macro",
], version = "0.1.0-alpha.0" }
[dependencies.windows]
workspace = true
features = ["Win32_Foundation"]
readme = "README.md"
[lints]
workspace = true
