[workspace]
resolver = "2"
members = [
    "plugin",
    "wslplugins-rs",
    "wslplugins-macro",
    "wslplugins-macro-core",
    "wslplugins-macro-tests",
]
[workspace.dependencies]
wslpluginapi-sys = "0.1.0-rc.1"
windows = "0.61.*"

[workspace.package]
authors = ["Mickaël Véril <mika.veril@wanadoo.fr>"]
version = "0.1.0-alpha.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mveril/wslplugins-rs"
description = "A Rust framework for developing WSL plugins using safe and idiomatic Rust."

[patch.crates-io]
wslpluginapi-sys = { version = "0.1.0-rc.1", git = "https://github.com/mveril/wslpluginapi-sys.git", branch = "feature/windows-sys-extra/windows-sys/Win32_Security_Authorization" }
