[workspace]
resolver = "2"
members = [
    "plugin",
    "wslplugins-rs",
    "wslplugins-macro",
    "wslplugins-macro-core",
    "wslplugins-macro-tests",
]

[workspace.package]
authors = ["Mickaël Véril <mika.veril@wanadoo.fr>"]
version = "0.1.0-alpha.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/mveril/wslplugins-rs"
description = "A Rust framework for developing WSL plugins using safe and idiomatic Rust."

[patch.crates-io]
wslpluginapi-sys = { git = "https://github.com/mveril/wslpluginapi-sys.git", branch = "release/0.1-beta.1+2.1.3" }
