[package]
name = "wslplugins-rs"
authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
edition = "2021"
keywords = ["wsl", "plugin", "windows", "linux"]
categories = ["os::windows-apis", "api-bindings", "virtualization"]
readme.workspace = true

[dependencies]
windows-core = { workspace = true }
bitflags = { version = ">0.1.0", optional = true }
enumflags2 = { version = ">0.5", optional = true }
flagset = { version = ">0.1.0", optional = true }
tracing = { version = "0.1.43", optional = true }
thiserror = "2.0.7"
typed-path = ">0.1"
widestring = { version = "1", features = ["alloc"] }
wslplugins-macro = { path = "../wslplugins-macro", optional = true, version = "0.1.0-alpha.0" }
wslpluginapi-sys.workspace = true
uuid = { version = "1", optional = true }
smallvec = { workspace = true, optional = true }


[dependencies.semver]
version = ">0.1"
optional = true

[dev-dependencies]
proptest = "1.9.0"
criterion = "0.8"

[features]
default = ["smallvec"]
sys = []
smallvec = ["dep:smallvec"]
macro = ["dep:wslplugins-macro", "sys", "tracing"]
tracing = ["dep:tracing"]
uuid = ["dep:uuid"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true


[[bench]]
name = "user_distribution_id_formatting"
harness = false
