[package]
name = "wslplugins-rs"
authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
edition = "2021"


[dependencies]
windows-core = "0.61.2"
bitflags = { version = ">0.1.0", optional = true }
enumflags2 = { version = ">0.5", optional = true }
flagset = { version = ">0.1.0", optional = true }
log = { version = "*", optional = true }
log-instrument = { version = "*", optional = true }
thiserror = "2.0.7"
typed-path = ">0.1"
widestring = { version = "1", features = ["alloc"] }
wslplugins-macro = { path = "../wslplugins-macro", optional = true }
wslpluginapi-sys.workspace = true

[dependencies.semver]
version = ">0.1"
optional = true

[features]
sys = []
log-full = ["log", "log-instrument"]
macro = ["dep:wslplugins-macro", "sys"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
