[package]
name = "unpackaged-distro-blacklist-policy"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
wslplugins-rs = { path = "../../crates/wslplugins-rs", features = [
  "macro",
  "bitflags",
  "tracing",
], version = "0.1.0-beta.4" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

[dependencies.windows]
workspace = true
features = ["Win32_Foundation"]

[lints]
workspace = true
