[package]
name = "wslplugins-macro-core"
authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"

[dependencies]
syn = { version = "*", features = ["full", "extra-traits"] }
quote = "*"
"proc-macro2" = "*"
heck = "0.5"
strum = { version = "0.26.3", features = ["derive"] }

[build-dependencies]
wslpluginapi-sys = { workspace = true, features = ["hooks-field-names"] }
quote = "*"
struct-field-names-as-array = "*"
