[package]
name = "plugin"
authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wslplugins-rs = { path = "../wslplugins-rs", features = [
  "macro",
  "bitflags",
  "log-full",
] }
chrono = "^0.*"
log = "0.4"
log-instrument = "0.3"
fern = "0.6"
etc-os-release = "0.1.0"
[dependencies.windows]
version = "0.58"
features = ["Win32_Foundation"]
