[package]
name = "wslplugins-macro-core"
authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"
description = "internal core implementation of for wslplugins-macro"
keywords = ["wsl", "plugin", "windows", "linux", "internal"]
categories = ["os::windows-apis", "api-bindings", "virtualization"]

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits"] }
quote = { workspace = true }
"proc-macro2" = { workspace = true }
heck = "0.5"
strum = { workspace = true }

[build-dependencies]
wslpluginapi-sys = { workspace = true, features = ["hooks-field-names"] }
quote = "1"
struct-field-names-as-array = "0.3"

[dev-dependencies]
proptest = "1.9.0"

[lints]
workspace = true
